version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./react:/app
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: backend
    environment:
      MONGO_URI: mongodb://mongo:27017/mymailapp
    volumes:
      - ./express:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: tars_mail_db
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"