# Use a Node.js LTS version as base image
FROM node:lts

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY ./express/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY ./express/ .

# Expose the port that the application will run on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
